package postgres

var AddrObjUpsertConfig = BatchUpsertConfig[AddrObj]{
	Table: "gar.as_addr_obj",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"name",
		"typename",
		"level",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"name",
		"typename",
		"level",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	Values: func(a AddrObj) []any {
		return []any{
			a.ID,
			a.ObjectID,
			a.ObjectGUID,
			a.ChangeID,
			a.Name,
			a.TypeName,
			a.Level,
			a.OperTypeID,
			a.PrevID,
			a.NextID,
			a.UpdateDate,
			a.StartDate,
			a.EndDate,
			a.IsActual,
			a.IsActive,
		}
	},
}
var AddrObjDivisionUpsertConfig = BatchUpsertConfig[AddrObjDivision]{
	Table: "gar.as_addr_obj_division",
	Columns: []string{
		"id",
		"parentid",
		"childid",
		"changeid",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"parentid",
		"childid",
		"changeid",
	},
	Values: func(a AddrObjDivision) []any {
		return []any{
			a.ID,
			a.ParentID,
			a.ChildID,
			a.ChangeID,
		}
	},
}

var AdmHierarchyUpsertConfig = BatchUpsertConfig[AdmHierarchy]{
	Table: "gar.as_adm_hierarchy",
	Columns: []string{
		"id",
		"objectid",
		"parentobjid",
		"changeid",
		"regioncode",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactive",
		"path",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"parentobjid",
		"changeid",
		"regioncode",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactive",
		"path",
	},
	Values: func(a AdmHierarchy) []any {
		return []any{
			a.ID,
			a.ObjectID,
			a.ParentObjID,
			a.ChangeID,
			a.RegionCode,
			a.PrevID,
			a.NextID,
			a.UpdateDate,
			a.StartDate,
			a.EndDate,
			a.IsActive,
			a.Path,
		}
	},
}

var ApartmentUpsertConfig = BatchUpsertConfig[Apartment]{
	Table: "gar.as_apartments",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"aparttype",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"aparttype",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	Values: func(a Apartment) []any {
		return []any{
			a.ID,
			a.ObjectID,
			a.ObjectGUID,
			a.ChangeID,
			a.Number,
			a.ApartType,
			a.OperTypeID,
			a.PrevID,
			a.NextID,
			a.UpdateDate,
			a.StartDate,
			a.EndDate,
			a.IsActual,
			a.IsActive,
		}
	},
}

var CarplaceUpsertConfig = BatchUpsertConfig[Carplace]{
	Table: "gar.as_carplaces",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
	},
	Values: func(c Carplace) []any {
		return []any{
			c.ID,
			c.ObjectID,
			c.ObjectGUID,
			c.ChangeID,
			c.Number,
			c.OperTypeID,
			c.PrevID,
			c.NextID,
			c.UpdateDate,
			c.StartDate,
			c.EndDate,
		}
	},
}

var ChangeHistoryUpsertConfig = BatchUpsertConfig[ChangeHistory]{
	Table: "gar.as_change_history",
	Columns: []string{
		"changeid",
		"objectid",
		"adrobjectid",
		"opertypeid",
		"ndocid",
		"changedate",
	},
	ConflictColumns: []string{"changeid"},
	UpdateColumns: []string{
		"objectid",
		"adrobjectid",
		"opertypeid",
		"ndocid",
		"changedate",
	},
	Values: func(c ChangeHistory) []any {
		return []any{
			c.ChangeID,
			c.ObjectID,
			c.AdrObjectID,
			c.OperTypeID,
			c.NDocID,
			c.ChangeDate,
		}
	},
}

var HouseUpsertConfig = BatchUpsertConfig[House]{
	Table: "gar.as_houses",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"housenum",
		"addnum1",
		"addnum2",
		"housetype",
		"addtype1",
		"addtype2",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"housenum",
		"addnum1",
		"addnum2",
		"housetype",
		"addtype1",
		"addtype2",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	Values: func(h House) []any {
		return []any{
			h.ID,
			h.ObjectID,
			h.ObjectGUID,
			h.ChangeID,
			h.HouseNum,
			h.AddNum1,
			h.AddNum2,
			h.HouseType,
			h.AddType1,
			h.AddType2,
			h.OperTypeID,
			h.PrevID,
			h.NextID,
			h.UpdateDate,
			h.StartDate,
			h.EndDate,
			h.IsActual,
			h.IsActive,
		}
	},
}
var MunHierarchyUpsertConfig = BatchUpsertConfig[MunHierarchy]{
	Table: "gar.as_mun_hierarchy",
	Columns: []string{
		"id",
		"objectid",
		"parentobjid",
		"changeid",
		"oktmo",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactive",
		"path",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"parentobjid",
		"changeid",
		"oktmo",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactive",
		"path",
	},
	Values: func(m MunHierarchy) []any {
		return []any{
			m.ID,
			m.ObjectID,
			m.ParentObjID,
			m.ChangeID,
			m.Oktmo,
			m.PrevID,
			m.NextID,
			m.UpdateDate,
			m.StartDate,
			m.EndDate,
			m.IsActive,
			m.Path,
		}
	},
}

var NormativeDocUpsertConfig = BatchUpsertConfig[NormativeDoc]{
	Table: "gar.as_normative_docs",
	Columns: []string{
		"id",
		"name",
		"date",
		"number",
		"type",
		"kind",
		"updatedate",
		"orgname",
		"regnum",
		"regdate",
		"accdate",
		"comment",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"name",
		"date",
		"number",
		"type",
		"kind",
		"updatedate",
		"orgname",
		"regnum",
		"regdate",
		"accdate",
		"comment",
	},
	Values: func(n NormativeDoc) []any {
		return []any{
			n.ID,
			n.Name,
			n.Date,
			n.Number,
			n.Type,
			n.Kind,
			n.UpdateDate,
			n.OrgName,
			n.RegNum,
			n.RegDate,
			n.AccDate,
			n.Comment,
		}
	},
}

var ReestrObjectUpsertConfig = BatchUpsertConfig[ReestrObject]{
	Table: "gar.as_reestr_objects",
	Columns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"isactive",
		"levelid",
		"createdate",
		"updatedate",
	},
	ConflictColumns: []string{"objectid"},
	UpdateColumns: []string{
		"objectguid",
		"changeid",
		"isactive",
		"levelid",
		"createdate",
		"updatedate",
	},
	Values: func(r ReestrObject) []any {
		return []any{
			r.ObjectID,
			r.ObjectGUID,
			r.ChangeID,
			r.IsActive,
			r.LevelID,
			r.CreateDate,
			r.UpdateDate,
		}
	},
}

var RoomUpsertConfig = BatchUpsertConfig[Room]{
	Table: "gar.as_rooms",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"roomtype",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"roomtype",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	Values: func(r Room) []any {
		return []any{
			r.ID,
			r.ObjectID,
			r.ObjectGUID,
			r.ChangeID,
			r.Number,
			r.RoomType,
			r.OperTypeID,
			r.PrevID,
			r.NextID,
			r.UpdateDate,
			r.StartDate,
			r.EndDate,
			r.IsActual,
			r.IsActive,
		}
	},
}

var SteadUpsertConfig = BatchUpsertConfig[Stead]{
	Table: "gar.as_steads",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	Values: func(s Stead) []any {
		return []any{
			s.ID,
			s.ObjectID,
			s.ObjectGUID,
			s.ChangeID,
			s.Number,
			s.OperTypeID,
			s.PrevID,
			s.NextID,
			s.UpdateDate,
			s.StartDate,
			s.EndDate,
			s.IsActual,
			s.IsActive,
		}
	},
}
