package postgres

var AddrObjUpsertConfig = BatchUpsertConfig[AddrObj]{
	Table: "gar.as_addr_obj",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"name",
		"typename",
		"level",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"name",
		"typename",
		"level",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	Values: func(a AddrObj) []any {
		return []any{
			a.ID,
			a.ObjectID,
			a.ObjectGUID,
			a.ChangeID,
			a.Name,
			a.TypeName,
			a.Level,
			a.OperTypeID,
			a.PrevID,
			a.NextID,
			a.UpdateDate,
			a.StartDate,
			a.EndDate,
			a.IsActual,
			a.IsActive,
		}
	},
}
var AddrObjDivisionUpsertConfig = BatchUpsertConfig[AddrObjDivision]{
	Table: "gar.as_addr_obj_division",
	Columns: []string{
		"id",
		"parentid",
		"childid",
		"changeid",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"parentid",
		"childid",
		"changeid",
	},
	Values: func(a AddrObjDivision) []any {
		return []any{
			a.ID,
			a.ParentID,
			a.ChildID,
			a.ChangeID,
		}
	},
}

var AdmHierarchyUpsertConfig = BatchUpsertConfig[AdmHierarchy]{
	Table: "gar.as_adm_hierarchy",
	Columns: []string{
		"id",
		"objectid",
		"parentobjid",
		"changeid",
		"regioncode",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactive",
		"path",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"parentobjid",
		"changeid",
		"regioncode",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactive",
		"path",
	},
	Values: func(a AdmHierarchy) []any {
		return []any{
			a.ID,
			a.ObjectID,
			a.ParentObjID,
			a.ChangeID,
			a.RegionCode,
			a.PrevID,
			a.NextID,
			a.UpdateDate,
			a.StartDate,
			a.EndDate,
			a.IsActive,
			a.Path,
		}
	},
}

var ApartmentUpsertConfig = BatchUpsertConfig[Apartment]{
	Table: "gar.as_apartments",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"aparttype",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"aparttype",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	Values: func(a Apartment) []any {
		return []any{
			a.ID,
			a.ObjectID,
			a.ObjectGUID,
			a.ChangeID,
			a.Number,
			a.ApartType,
			a.OperTypeID,
			a.PrevID,
			a.NextID,
			a.UpdateDate,
			a.StartDate,
			a.EndDate,
			a.IsActual,
			a.IsActive,
		}
	},
}

var CarplaceUpsertConfig = BatchUpsertConfig[Carplace]{
	Table: "gar.as_carplaces",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"number",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
	},
	Values: func(c Carplace) []any {
		return []any{
			c.ID,
			c.ObjectID,
			c.ObjectGUID,
			c.ChangeID,
			c.Number,
			c.OperTypeID,
			c.PrevID,
			c.NextID,
			c.UpdateDate,
			c.StartDate,
			c.EndDate,
		}
	},
}

var ChangeHistoryUpsertConfig = BatchUpsertConfig[ChangeHistory]{
	Table: "gar.as_change_history",
	Columns: []string{
		"changeid",
		"objectid",
		"adrobjectid",
		"opertypeid",
		"ndocid",
		"changedate",
	},
	ConflictColumns: []string{"changeid"},
	UpdateColumns: []string{
		"objectid",
		"adrobjectid",
		"opertypeid",
		"ndocid",
		"changedate",
	},
	Values: func(c ChangeHistory) []any {
		return []any{
			c.ChangeID,
			c.ObjectID,
			c.AdrObjectID,
			c.OperTypeID,
			c.NDocID,
			c.ChangeDate,
		}
	},
}

var HouseUpsertConfig = BatchUpsertConfig[House]{
	Table: "gar.as_houses",
	Columns: []string{
		"id",
		"objectid",
		"objectguid",
		"changeid",
		"housenum",
		"addnum1",
		"addnum2",
		"housetype",
		"addtype1",
		"addtype2",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	ConflictColumns: []string{"id"},
	UpdateColumns: []string{
		"objectid",
		"objectguid",
		"changeid",
		"housenum",
		"addnum1",
		"addnum2",
		"housetype",
		"addtype1",
		"addtype2",
		"opertypeid",
		"previd",
		"nextid",
		"updatedate",
		"startdate",
		"enddate",
		"isactual",
		"isactive",
	},
	Values: func(h House) []any {
		return []any{
			h.ID,
			h.ObjectID,
			h.ObjectGUID,
			h.ChangeID,
			h.HouseNum,
			h.AddNum1,
			h.AddNum2,
			h.HouseType,
			h.AddType1,
			h.AddType2,
			h.OperTypeID,
			h.PrevID,
			h.NextID,
			h.UpdateDate,
			h.StartDate,
			h.EndDate,
			h.IsActual,
			h.IsActive,
		}
	},
}
